// Global app actions
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_ORGS = 'REQUEST_ORGS';
export const RECEIVE_ORGS = 'RECEIVE_ORGS';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

// Home actions
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const CREATE_ORG_REQUEST = 'CREATE_ORG_REQUEST';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// Inventory Actions
export const REQUEST_INVENTORY_LIST = 'REQUEST_INVENTORY_LIST';
export const SET_INVENTORY_LIST = 'SET_INVENTORY_LIST';

export const REQUEST_INVENTORY = 'REQUEST_INVENTORY';
export const SET_INVENTORY = 'SET_INVENTORY';

export const REQUEST_UPDATE_INVENTORY = 'REQUEST_UPDATE_INVENTORY';
export const REQUEST_CREATE_INVENTORY = 'REQUEST_CREATE_INVENTORY';

// Transaction actions
export const REQUEST_TRANSACTION_LIST = 'REQUEST_TRANSACTION_LIST';
export const SET_TRANSACTION_LIST = 'SET_TRANSACTION_LIST';

export const REQUEST_UPDATE_TRANSACTION = 'REQUEST_UPDATE_TRANSACTION';

// Request actions
export const REQUEST_REQUEST_LIST = 'REQUEST_REQUEST_LIST';
export const SET_REQUEST_LIST = 'SET_REQUEST_LIST';

export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';
