// Global app actions
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_ORGS = 'REQUEST_ORGS';
export const RECEIVE_ORGS = 'RECEIVE_ORGS';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';

// Home actions
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const CREATE_ORG_REQUEST = 'CREATE_ORG_REQUEST';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';
