# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: idin-cloud-func

# Remember to install project dependencies to register the provider plugin.
# $ npm install
provider:
  name: openwhisk

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          method: GET
          path: /hello-world
          resp: json

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk

resources:
  apigw:
    name: 'idin-cloud-func'
    basepath: '/api'
    cors: true
